----------------------------------
---NovaRaidCompanion Talent Data--
----------------------------------

local addonName, NRC = ...;
if (not NRC.isMOP) then
	return;
end

--This specData table isn't really used for MoP since we get it all from api but leaving it here anyway.
local specData = {
	--classID.
	[1] = {
		name = "WARRIOR",
		icon = 626008,
		iconPath = "Interface\\Icons\\ClassIcon_Warrior",
		--Specs, id is from talent book left to right.
		[1] = {
			name = "Arms",
			icon = 132219,
			iconPath = "Interface\\Icons\\Ability_Kick",
		},
		[2] = {
			name = "Fury",
			icon = 132347,
			iconPath = "Interface\\Icons\\Ability_Warrior_InnerRage",
		},
		[3] = {
			name = "Protection",
			icon = 132341,
			iconPath = "Interface\\Icons\\Ability_Warrior_DefensiveStance",
		},
	},
	[2] = {
		name = "PALADIN",
		icon = 626003,
		iconPath = "Interface\\Icons\\ClassIcon_Paladin",
		[1] = {
			name = "Holy",
			icon = 135920,
			iconPath = "Interface\\Icons\\Spell_Holy_HolyBolt",
		},
		[2] = {
			name = "Protection",
			icon = 135893,
			iconPath = "Interface\\Icons\\SPELL_HOLY_DEVOTIONAURA",
		},
		[3] = {
			name = "Retribution",
			icon = 135873,
			iconPath = "Interface\\Icons\\Spell_Holy_AuraOfLight",
		},
	},
	[3] = {
		name = "HUNTER",
		icon = 626000,
		iconPath = "Interface\\Icons\\ClassIcon_Hunter",
		[1] = {
			name = "Beast Mastery",
			icon = 132164,
			iconPath = "Interface\\Icons\\Ability_Hunter_BeastTaming",
		},
		[2] = {
			name = "Marksmanship",
			icon = 132222,
			iconPath = "Interface\\Icons\\Ability_Marksmanship",
		},
		[3] = {
			name = "Survival",
			icon = 132215,
			iconPath = "Interface\\Icons\\Ability_Hunter_SwiftStrike",
		},
	},
	[4] = {
		name = "ROGUE",
		icon = 626005,
		iconPath = "Interface\\Icons\\ClassIcon_Rogue",
		[1] = {
			name = "Assassination",
			icon = 132292,
			iconPath = "Interface\\Icons\\Ability_Rogue_Eviscerate",
		},
		[2] = {
			name = "Combat",
			icon = 132090,
			iconPath = "Interface\\Icons\\Ability_BackStab",
		},
		[3] = {
			name = "Subtlety",
			icon = 132320,
			iconPath = "Interface\\Icons\\Ability_Stealth",
		},
	},
	[5] = {
		name = "PRIEST",
		icon = 626004,
		iconPath = "Interface\\Icons\\ClassIcon_Priest",
		[1] = {
			name = "Discipline",
			icon = 135940,
			iconPath = "Interface\\Icons\\spell_holy_powerwordshield",
		},
		[2] = {
			name = "Holy",
			--icon = 135920, --Classic/TBC
			--iconPath = "Interface\\Icons\\Spell_Holy_HolyBolt",
			--icon = 237542, --Better holy priest icon but doesn't exist in Classic/TBC.
			--iconPath = "Interface\\Icons\\Spell_Holy_GuardianSpirit",
			--Use addon path for both, should be fine as icon is just for setextures for now.
			icon = "Interface\\AddOns\\NovaRaidCompanion\\Media\\Blizzard\\Spell_Holy_GuardianSpirit",
			iconPath = "Interface\\AddOns\\NovaRaidCompanion\\Media\\Blizzard\\Spell_Holy_GuardianSpirit",
		},
		[3] = {
			name = "Shadow",
			icon = 136207,
			iconPath = "Interface\\Icons\\Spell_Shadow_ShadowWordPain",
		},
	},
	[6] = {
		name = "DEATHKNIGHT",
		icon = 135771,
		iconPath = "Interface\\Icons\\ClassIcon_DeathKnight",
		[1] = {
			name = "Blood",
			icon = 135770,
			iconPath = "Interface\\Icons\\Spell_Deathknight_BloodPresence",
		},
		[2] = {
			name = "Frost",
			icon = 135773,
			iconPath = "Interface\\Icons\\Spell_Deathknight_FrostPresence",
		},
		[3] = {
			name = "Unholy",
			icon = 135775,
			iconPath = "Interface\\Icons\\Spell_Deathknight_UnholyPresence",
		},
	},
	[7] = {
		name = "SHAMAN",
		icon = 626006,
		iconPath = "Interface\\Icons\\ClassIcon_Shaman",
		[1] = {
			name = "Elemental",
			icon = 136048,
			iconPath = "Interface\\Icons\\Spell_Nature_Lightning",
		},
		[2] = {
			name = "Enhancement",
			icon = 136051,
			iconPath = "Interface\\Icons\\Spell_Nature_LightningShield",
		},
		[3] = {
			name = "Restoration",
			icon = 136052,
			iconPath = "Interface\\Icons\\Spell_Nature_MagicImmunity",
		},
	},
	[8] = {
		name = "MAGE",
		icon = 626001,
		iconPath = "Interface\\Icons\\ClassIcon_Mage",
		[1] = {
			name = "Arcane",
			icon = 135932,
			iconPath = "Interface\\Icons\\Spell_Holy_MagicalSentry",
		},
		[2] = {
			name = "Fire",
			icon = 135810,
			iconPath = "Interface\\Icons\\Spell_Fire_FireBolt02",
		},
		[3] = {
			name = "Frost",
			icon = 135846,
			iconPath = "Interface\\Icons\\Spell_Frost_FrostBolt02",
		},
	},
	[9] = {
		name = "WARLOCK",
		icon = 626007,
		iconPath = "Interface\\Icons\\ClassIcon_Warlock",
		--Specs, id is from talent book left to right.
		[1] = {
			name = "Affliction",
			icon = 136145,
			iconPath = "Interface\\Icons\\Spell_Shadow_DeathCoil",
		},
		[2] = {
			name = "Demonology",
			icon = 136172,
			iconPath = "Interface\\Icons\\Spell_Shadow_Metamorphosis",
		},
		[3] = {
			name = "Destruction",
			icon = 136186,
			iconPath = "Interface\\Icons\\Spell_Shadow_RainOfFire",
		},
	},
	[10] = {
		name = "MONK",
		icon = 136830,
		iconPath = "Interface\\Icons\\ClassIcon_Monk",
		[1] = {
			name = "Brewmaster",
			icon = 608951,
			iconPath = "Interface\\Icons\\Spell_Monk_Brewmaster_Spec",
		},
		[2] = {
			name = "Mistweaver",
			icon = 608952,
			iconPath = "Interface\\Icons\\Spell_Monk_MistWeaver_Spec",
		},
		[3] = {
			name = "Windwalker",
			icon = 608953,
			iconPath = "Interface\\Icons\\Spell_Monk_WindWalker_Spec",
		},
	},
	[11] = {
		name = "DRUID",
		icon = 625999,
		iconPath = "Interface\\Icons\\ClassIcon_Druid",
		[1] = {
			name = "Balance",
			icon = 136096,
			iconPath = "Interface\\Icons\\Spell_Nature_StarFall",
		},
		[2] = {
			name = "Feral",
			icon = 132276,
			iconPath = "Interface\\Icons\\Ability_Racial_BearForm",
		},
		[3] = {
			name = "Guardian",
			icon = 132276,
			iconPath = "Interface\\Icons\\Ability_Racial_BearForm",
		},
		[4] = { --Needs changing to 4 once druids gain 4th spec.
			name = "Restoration",
			icon = 136041,
			iconPath = "Interface\\Icons\\SPELL_NATURE_HEALINGTOUCH",
		},
	},
};

--Exported by NRC talent exporter.
--Sorted by row and then 3 column entries for each tier.
local talents = {};
talents.deathknight = {
    [1] = {
        [1] = {
            ["name"] = "Roiling Blood",
            ["row"] = 1,
            ["column"] = 1,
            ["talentID"] = 19165,
            ["spellID"] = 108170,
            ["icon"] = 538561,
        },
        [2] = {
            ["name"] = "Plague Leech",
            ["row"] = 1,
            ["column"] = 2,
            ["talentID"] = 19166,
            ["spellID"] = 123693,
            ["icon"] = 132099,
        },
        [3] = {
            ["name"] = "Unholy Blight",
            ["row"] = 1,
            ["column"] = 3,
            ["talentID"] = 19217,
            ["spellID"] = 115989,
            ["icon"] = 136132,
        },
    },
    [2] = {
        [1] = {
            ["name"] = "Lichborne",
            ["row"] = 2,
            ["column"] = 1,
            ["talentID"] = 19218,
            ["spellID"] = 49039,
            ["icon"] = 136187,
        },
        [2] = {
            ["name"] = "Anti-Magic Zone",
            ["row"] = 2,
            ["column"] = 2,
            ["talentID"] = 19219,
            ["spellID"] = 51052,
            ["icon"] = 237510,
        },
        [3] = {
            ["name"] = "Purgatory",
            ["row"] = 2,
            ["column"] = 3,
            ["talentID"] = 19220,
            ["spellID"] = 114556,
            ["icon"] = 134430,
        },
    },
    [3] = {
        [1] = {
            ["name"] = "Death's Advance",
            ["row"] = 3,
            ["column"] = 1,
            ["talentID"] = 19221,
            ["spellID"] = 96268,
            ["icon"] = 237561,
        },
        [2] = {
            ["name"] = "Chilblains",
            ["row"] = 3,
            ["column"] = 2,
            ["talentID"] = 19222,
            ["spellID"] = 50041,
            ["icon"] = 135864,
        },
        [3] = {
            ["name"] = "Asphyxiate",
            ["row"] = 3,
            ["column"] = 3,
            ["talentID"] = 19223,
            ["spellID"] = 108194,
            ["icon"] = 538558,
        },
    },
    [4] = {
        [1] = {
            ["name"] = "Death Pact",
            ["row"] = 4,
            ["column"] = 1,
            ["talentID"] = 19224,
            ["spellID"] = 48743,
            ["icon"] = 136146,
        },
        [2] = {
            ["name"] = "Death Siphon",
            ["row"] = 4,
            ["column"] = 2,
            ["talentID"] = 19225,
            ["spellID"] = 108196,
            ["icon"] = 538559,
        },
        [3] = {
            ["name"] = "Conversion",
            ["row"] = 4,
            ["column"] = 3,
            ["talentID"] = 19229,
            ["spellID"] = 119975,
            ["icon"] = 538560,
        },
    },
    [5] = {
        [1] = {
            ["name"] = "Blood Tap",
            ["row"] = 5,
            ["column"] = 1,
            ["talentID"] = 19226,
            ["spellID"] = 45529,
            ["icon"] = 237515,
        },
        [2] = {
            ["name"] = "Runic Empowerment",
            ["row"] = 5,
            ["column"] = 2,
            ["talentID"] = 19227,
            ["spellID"] = 81229,
            ["icon"] = 134423,
        },
        [3] = {
            ["name"] = "Runic Corruption",
            ["row"] = 5,
            ["column"] = 3,
            ["talentID"] = 19228,
            ["spellID"] = 51462,
            ["icon"] = 252272,
        },
    },
    [6] = {
        [1] = {
            ["name"] = "Gorefiend's Grasp",
            ["row"] = 6,
            ["column"] = 1,
            ["talentID"] = 19230,
            ["spellID"] = 108199,
            ["icon"] = 538767,
        },
        [2] = {
            ["name"] = "Remorseless Winter",
            ["row"] = 6,
            ["column"] = 2,
            ["talentID"] = 19231,
            ["spellID"] = 108200,
            ["icon"] = 538770,
        },
        [3] = {
            ["name"] = "Desecrated Ground",
            ["row"] = 6,
            ["column"] = 3,
            ["talentID"] = 19232,
            ["spellID"] = 108201,
            ["icon"] = 538768,
        },
    },
};

talents.druid = {
    [1] = {
        [1] = {
            ["name"] = "Feline Swiftness",
            ["row"] = 1,
            ["column"] = 1,
            ["talentID"] = 18569,
            ["spellID"] = 131768,
            ["icon"] = 538517,
        },
        [2] = {
            ["name"] = "Displacer Beast",
            ["row"] = 1,
            ["column"] = 2,
            ["talentID"] = 18570,
            ["spellID"] = 102280,
            ["icon"] = 538514,
        },
        [3] = {
            ["name"] = "Wild Charge",
            ["row"] = 1,
            ["column"] = 3,
            ["talentID"] = 18571,
            ["spellID"] = 102401,
            ["icon"] = 538771,
        },
    },
    [2] = {
        [1] = {
            ["name"] = "Ysera's Gift",
            ["row"] = 2,
            ["column"] = 1,
            ["talentID"] = 18572,
            ["spellID"] = 145108,
            ["icon"] = 134157,
        },
        [2] = {
            ["name"] = "Renewal",
            ["row"] = 2,
            ["column"] = 2,
            ["talentID"] = 19283,
            ["spellID"] = 108238,
            ["icon"] = 136059,
        },
        [3] = {
            ["name"] = "Cenarion Ward",
            ["row"] = 2,
            ["column"] = 3,
            ["talentID"] = 18574,
            ["spellID"] = 102351,
            ["icon"] = 132137,
        },
    },
    [3] = {
        [1] = {
            ["name"] = "Faerie Swarm",
            ["row"] = 3,
            ["column"] = 1,
            ["talentID"] = 18575,
            ["spellID"] = 106707,
            ["icon"] = 538516,
        },
        [2] = {
            ["name"] = "Mass Entanglement",
            ["row"] = 3,
            ["column"] = 2,
            ["talentID"] = 18576,
            ["spellID"] = 102359,
            ["icon"] = 538515,
        },
        [3] = {
            ["name"] = "Typhoon",
            ["row"] = 3,
            ["column"] = 3,
            ["talentID"] = 18577,
            ["spellID"] = 132469,
            ["icon"] = 236170,
        },
    },
    [4] = {
        [1] = {
            ["name"] = "Soul of the Forest",
            ["row"] = 4,
            ["column"] = 1,
            ["talentID"] = 19677,
            ["spellID"] = 114107,
            ["icon"] = 236160,
        },
        [2] = {
            ["name"] = "Incarnation",
            ["row"] = 4,
            ["column"] = 2,
            ["talentID"] = 18579,
            ["spellID"] = 106731,
            ["icon"] = 571586,
        },
        [3] = {
            ["name"] = "Force of Nature",
            ["row"] = 4,
            ["column"] = 3,
            ["talentID"] = 18580,
            ["spellID"] = 106737,
            ["icon"] = 132129,
        },
    },
    [5] = {
        [1] = {
            ["name"] = "Disorienting Roar",
            ["row"] = 5,
            ["column"] = 1,
            ["talentID"] = 18581,
            ["spellID"] = 99,
            ["icon"] = 132121,
        },
        [2] = {
            ["name"] = "Ursol's Vortex",
            ["row"] = 5,
            ["column"] = 2,
            ["talentID"] = 18582,
            ["spellID"] = 102793,
            ["icon"] = 571588,
        },
        [3] = {
            ["name"] = "Mighty Bash",
            ["row"] = 5,
            ["column"] = 3,
            ["talentID"] = 18583,
            ["spellID"] = 5211,
            ["icon"] = 132114,
        },
    },
    [6] = {
        [1] = {
            ["name"] = "Heart of the Wild",
            ["row"] = 6,
            ["column"] = 1,
            ["talentID"] = 18584,
            ["spellID"] = 108288,
            ["icon"] = 135879,
        },
        [2] = {
            ["name"] = "Dream of Cenarius",
            ["row"] = 6,
            ["column"] = 2,
            ["talentID"] = 18585,
            ["spellID"] = 108373,
            ["icon"] = 132123,
        },
        [3] = {
            ["name"] = "Nature's Vigil",
            ["row"] = 6,
            ["column"] = 3,
            ["talentID"] = 18586,
            ["spellID"] = 124974,
            ["icon"] = 236764,
        },
    },
};

talents.hunter = {
    [1] = {
        [1] = {
            ["name"] = "Posthaste",
            ["row"] = 1,
            ["column"] = 1,
            ["talentID"] = 19354,
            ["spellID"] = 109215,
            ["icon"] = 461119,
        },
        [2] = {
            ["name"] = "Narrow Escape",
            ["row"] = 1,
            ["column"] = 2,
            ["talentID"] = 19363,
            ["spellID"] = 109298,
            ["icon"] = 237430,
        },
        [3] = {
            ["name"] = "Crouching Tiger, Hidden Chimera",
            ["row"] = 1,
            ["column"] = 3,
            ["talentID"] = 19364,
            ["spellID"] = 118675,
            ["icon"] = 236190,
        },
    },
    [2] = {
        [1] = {
            ["name"] = "Binding Shot",
            ["row"] = 2,
            ["column"] = 1,
            ["talentID"] = 19347,
            ["spellID"] = 109248,
            ["icon"] = 462650,
        },
        [2] = {
            ["name"] = "Wyvern Sting",
            ["row"] = 2,
            ["column"] = 2,
            ["talentID"] = 19348,
            ["spellID"] = 19386,
            ["icon"] = 135125,
        },
        [3] = {
            ["name"] = "Intimidation",
            ["row"] = 2,
            ["column"] = 3,
            ["talentID"] = 19359,
            ["spellID"] = 19577,
            ["icon"] = 132111,
        },
    },
    [3] = {
        [1] = {
            ["name"] = "Exhilaration",
            ["row"] = 3,
            ["column"] = 1,
            ["talentID"] = 19350,
            ["spellID"] = 109304,
            ["icon"] = 461117,
        },
        [2] = {
            ["name"] = "Aspect of the Iron Hawk",
            ["row"] = 3,
            ["column"] = 2,
            ["talentID"] = 19356,
            ["spellID"] = 109260,
            ["icon"] = 612363,
        },
        [3] = {
            ["name"] = "Spirit Bond",
            ["row"] = 3,
            ["column"] = 3,
            ["talentID"] = 19351,
            ["spellID"] = 109212,
            ["icon"] = 132121,
        },
    },
    [4] = {
        [1] = {
            ["name"] = "Fervor",
            ["row"] = 4,
            ["column"] = 1,
            ["talentID"] = 19352,
            ["spellID"] = 82726,
            ["icon"] = 132160,
        },
        [2] = {
            ["name"] = "Dire Beast",
            ["row"] = 4,
            ["column"] = 2,
            ["talentID"] = 19353,
            ["spellID"] = 120679,
            ["icon"] = 461121,
        },
        [3] = {
            ["name"] = "Thrill of the Hunt",
            ["row"] = 4,
            ["column"] = 3,
            ["talentID"] = 19365,
            ["spellID"] = 109306,
            ["icon"] = 132216,
        },
    },
    [5] = {
        [1] = {
            ["name"] = "A Murder of Crows",
            ["row"] = 5,
            ["column"] = 1,
            ["talentID"] = 19360,
            ["spellID"] = 131894,
            ["icon"] = 645217,
        },
        [2] = {
            ["name"] = "Blink Strikes",
            ["row"] = 5,
            ["column"] = 2,
            ["talentID"] = 19361,
            ["spellID"] = 130392,
            ["icon"] = 135731,
        },
        [3] = {
            ["name"] = "Lynx Rush",
            ["row"] = 5,
            ["column"] = 3,
            ["talentID"] = 19362,
            ["spellID"] = 120697,
            ["icon"] = 132167,
        },
    },
    [6] = {
        [1] = {
            ["name"] = "Glaive Toss",
            ["row"] = 6,
            ["column"] = 1,
            ["talentID"] = 19357,
            ["spellID"] = 117050,
            ["icon"] = 648707,
        },
        [2] = {
            ["name"] = "Powershot",
            ["row"] = 6,
            ["column"] = 2,
            ["talentID"] = 19358,
            ["spellID"] = 109259,
            ["icon"] = 461120,
        },
        [3] = {
            ["name"] = "Barrage",
            ["row"] = 6,
            ["column"] = 3,
            ["talentID"] = 19349,
            ["spellID"] = 120360,
            ["icon"] = 236201,
        },
    },
};

talents.mage = {
    [1] = {
        [1] = {
            ["name"] = "Presence of Mind",
            ["row"] = 1,
            ["column"] = 1,
            ["talentID"] = 16011,
            ["spellID"] = 12043,
            ["icon"] = 136031,
        },
        [2] = {
            ["name"] = "Blazing Speed",
            ["row"] = 1,
            ["column"] = 2,
            ["talentID"] = 16012,
            ["spellID"] = 108843,
            ["icon"] = 135788,
        },
        [3] = {
            ["name"] = "Ice Floes",
            ["row"] = 1,
            ["column"] = 3,
            ["talentID"] = 16013,
            ["spellID"] = 108839,
            ["icon"] = 610877,
        },
    },
    [2] = {
        [1] = {
            ["name"] = "Temporal Shield",
            ["row"] = 2,
            ["column"] = 1,
            ["talentID"] = 16023,
            ["spellID"] = 115610,
            ["icon"] = 610472,
        },
        [2] = {
            ["name"] = "Flameglow",
            ["row"] = 2,
            ["column"] = 2,
            ["talentID"] = 16024,
            ["spellID"] = 140468,
            ["icon"] = 132847,
        },
        [3] = {
            ["name"] = "Ice Barrier",
            ["row"] = 2,
            ["column"] = 3,
            ["talentID"] = 16025,
            ["spellID"] = 11426,
            ["icon"] = 135988,
        },
    },
    [3] = {
        [1] = {
            ["name"] = "Ring of Frost",
            ["row"] = 3,
            ["column"] = 1,
            ["talentID"] = 16019,
            ["spellID"] = 113724,
            ["icon"] = 464484,
        },
        [2] = {
            ["name"] = "Ice Ward",
            ["row"] = 3,
            ["column"] = 2,
            ["talentID"] = 16020,
            ["spellID"] = 111264,
            ["icon"] = 135850,
        },
        [3] = {
            ["name"] = "Frostjaw",
            ["row"] = 3,
            ["column"] = 3,
            ["talentID"] = 16021,
            ["spellID"] = 102051,
            ["icon"] = 538562,
        },
    },
    [4] = {
        [1] = {
            ["name"] = "Greater Invisibility",
            ["row"] = 4,
            ["column"] = 1,
            ["talentID"] = 16027,
            ["spellID"] = 110959,
            ["icon"] = 575584,
        },
        [2] = {
            ["name"] = "Cauterize",
            ["row"] = 4,
            ["column"] = 2,
            ["talentID"] = 16028,
            ["spellID"] = 86949,
            ["icon"] = 252268,
        },
        [3] = {
            ["name"] = "Cold Snap",
            ["row"] = 4,
            ["column"] = 3,
            ["talentID"] = 16029,
            ["spellID"] = 11958,
            ["icon"] = 135865,
        },
    },
    [5] = {
        [1] = {
            ["name"] = "Nether Tempest",
            ["row"] = 5,
            ["column"] = 1,
            ["talentID"] = 19299,
            ["spellID"] = 114923,
            ["icon"] = 610471,
        },
        [2] = {
            ["name"] = "Living Bomb",
            ["row"] = 5,
            ["column"] = 2,
            ["talentID"] = 19300,
            ["spellID"] = 44457,
            ["icon"] = 236220,
        },
        [3] = {
            ["name"] = "Frost Bomb",
            ["row"] = 5,
            ["column"] = 3,
            ["talentID"] = 19301,
            ["spellID"] = 112948,
            ["icon"] = 609814,
        },
    },
    [6] = {
        [1] = {
            ["name"] = "Invocation",
            ["row"] = 6,
            ["column"] = 1,
            ["talentID"] = 16031,
            ["spellID"] = 114003,
            ["icon"] = 135730,
        },
        [2] = {
            ["name"] = "Rune of Power",
            ["row"] = 6,
            ["column"] = 2,
            ["talentID"] = 16032,
            ["spellID"] = 116011,
            ["icon"] = 609815,
        },
        [3] = {
            ["name"] = "Incanter's Ward",
            ["row"] = 6,
            ["column"] = 3,
            ["talentID"] = 16033,
            ["spellID"] = 1463,
            ["icon"] = 136153,
        },
    },
};

talents.monk = {
    [1] = {
        [1] = {
            ["name"] = "Celerity",
            ["row"] = 1,
            ["column"] = 1,
            ["talentID"] = 19302,
            ["spellID"] = 115173,
            ["icon"] = 607848,
        },
        [2] = {
            ["name"] = "Tiger's Lust",
            ["row"] = 1,
            ["column"] = 2,
            ["talentID"] = 19818,
            ["spellID"] = 116841,
            ["icon"] = 651727,
        },
        [3] = {
            ["name"] = "Momentum",
            ["row"] = 1,
            ["column"] = 3,
            ["talentID"] = 19304,
            ["spellID"] = 115174,
            ["icon"] = 574577,
        },
    },
    [2] = {
        [1] = {
            ["name"] = "Chi Wave",
            ["row"] = 2,
            ["column"] = 1,
            ["talentID"] = 20185,
            ["spellID"] = 115098,
            ["icon"] = 606541,
        },
        [2] = {
            ["name"] = "Zen Sphere",
            ["row"] = 2,
            ["column"] = 2,
            ["talentID"] = 19820,
            ["spellID"] = 124081,
            ["icon"] = 613397,
        },
        [3] = {
            ["name"] = "Chi Burst",
            ["row"] = 2,
            ["column"] = 3,
            ["talentID"] = 19823,
            ["spellID"] = 123986,
            ["icon"] = 135734,
        },
    },
    [3] = {
        [1] = {
            ["name"] = "Power Strikes",
            ["row"] = 3,
            ["column"] = 1,
            ["talentID"] = 19992,
            ["spellID"] = 121817,
            ["icon"] = 629484,
        },
        [2] = {
            ["name"] = "Ascension",
            ["row"] = 3,
            ["column"] = 2,
            ["talentID"] = 19771,
            ["spellID"] = 115396,
            ["icon"] = 629482,
        },
        [3] = {
            ["name"] = "Chi Brew",
            ["row"] = 3,
            ["column"] = 3,
            ["talentID"] = 19772,
            ["spellID"] = 115399,
            ["icon"] = 629483,
        },
    },
    [4] = {
        [1] = {
            ["name"] = "Ring of Peace",
            ["row"] = 4,
            ["column"] = 1,
            ["talentID"] = 19993,
            ["spellID"] = 116844,
            ["icon"] = 839107,
        },
        [2] = {
            ["name"] = "Charging Ox Wave",
            ["row"] = 4,
            ["column"] = 2,
            ["talentID"] = 19994,
            ["spellID"] = 119392,
            ["icon"] = 615340,
        },
        [3] = {
            ["name"] = "Leg Sweep",
            ["row"] = 4,
            ["column"] = 3,
            ["talentID"] = 19995,
            ["spellID"] = 119381,
            ["icon"] = 642414,
        },
    },
    [5] = {
        [1] = {
            ["name"] = "Healing Elixirs",
            ["row"] = 5,
            ["column"] = 1,
            ["talentID"] = 20174,
            ["spellID"] = 122280,
            ["icon"] = 608939,
        },
        [2] = {
            ["name"] = "Dampen Harm",
            ["row"] = 5,
            ["column"] = 2,
            ["talentID"] = 20175,
            ["spellID"] = 122278,
            ["icon"] = 620827,
        },
        [3] = {
            ["name"] = "Diffuse Magic",
            ["row"] = 5,
            ["column"] = 3,
            ["talentID"] = 20173,
            ["spellID"] = 122783,
            ["icon"] = 775460,
        },
    },
    [6] = {
        [1] = {
            ["name"] = "Rushing Jade Wind",
            ["row"] = 6,
            ["column"] = 1,
            ["talentID"] = 19819,
            ["spellID"] = 116847,
            ["icon"] = 606549,
        },
        [2] = {
            ["name"] = "Invoke Xuen, the White Tiger",
            ["row"] = 6,
            ["column"] = 2,
            ["talentID"] = 20184,
            ["spellID"] = 123904,
            ["icon"] = 620832,
        },
        [3] = {
            ["name"] = "Chi Torpedo",
            ["row"] = 6,
            ["column"] = 3,
            ["talentID"] = 19313,
            ["spellID"] = 115008,
            ["icon"] = 607849,
        },
    },
};

talents.paladin = {
    [1] = {
        [1] = {
            ["name"] = "Speed of Light",
            ["row"] = 1,
            ["column"] = 1,
            ["talentID"] = 17565,
            ["spellID"] = 85499,
            ["icon"] = 571558,
        },
        [2] = {
            ["name"] = "Long Arm of the Law",
            ["row"] = 1,
            ["column"] = 2,
            ["talentID"] = 17567,
            ["spellID"] = 87172,
            ["icon"] = 571556,
        },
        [3] = {
            ["name"] = "Pursuit of Justice",
            ["row"] = 1,
            ["column"] = 3,
            ["talentID"] = 17569,
            ["spellID"] = 26023,
            ["icon"] = 589117,
        },
    },
    [2] = {
        [1] = {
            ["name"] = "Fist of Justice",
            ["row"] = 2,
            ["column"] = 1,
            ["talentID"] = 17573,
            ["spellID"] = 105593,
            ["icon"] = 135906,
        },
        [2] = {
            ["name"] = "Repentance",
            ["row"] = 2,
            ["column"] = 2,
            ["talentID"] = 17575,
            ["spellID"] = 20066,
            ["icon"] = 135942,
        },
        [3] = {
            ["name"] = "Evil is a Point of View",
            ["row"] = 2,
            ["column"] = 3,
            ["talentID"] = 17577,
            ["spellID"] = 110301,
            ["icon"] = 571559,
        },
    },
    [3] = {
        [1] = {
            ["name"] = "Selfless Healer",
            ["row"] = 3,
            ["column"] = 1,
            ["talentID"] = 17581,
            ["spellID"] = 85804,
            ["icon"] = 236252,
        },
        [2] = {
            ["name"] = "Eternal Flame",
            ["row"] = 3,
            ["column"] = 2,
            ["talentID"] = 17583,
            ["spellID"] = 114163,
            ["icon"] = 135433,
        },
        [3] = {
            ["name"] = "Sacred Shield",
            ["row"] = 3,
            ["column"] = 3,
            ["talentID"] = 21098,
            ["spellID"] = 20925,
            ["icon"] = 236249,
        },
    },
    [4] = {
        [1] = {
            ["name"] = "Hand of Purity",
            ["row"] = 4,
            ["column"] = 1,
            ["talentID"] = 17589,
            ["spellID"] = 114039,
            ["icon"] = 135970,
        },
        [2] = {
            ["name"] = "Unbreakable Spirit",
            ["row"] = 4,
            ["column"] = 2,
            ["talentID"] = 17591,
            ["spellID"] = 114154,
            ["icon"] = 135984,
        },
        [3] = {
            ["name"] = "Clemency",
            ["row"] = 4,
            ["column"] = 3,
            ["talentID"] = 17593,
            ["spellID"] = 105622,
            ["icon"] = 589116,
        },
    },
    [5] = {
        [1] = {
            ["name"] = "Holy Avenger",
            ["row"] = 5,
            ["column"] = 1,
            ["talentID"] = 17597,
            ["spellID"] = 105809,
            ["icon"] = 571555,
        },
        [2] = {
            ["name"] = "Sanctified Wrath",
            ["row"] = 5,
            ["column"] = 2,
            ["talentID"] = 17599,
            ["spellID"] = 53376,
            ["icon"] = 236262,
        },
        [3] = {
            ["name"] = "Divine Purpose",
            ["row"] = 5,
            ["column"] = 3,
            ["talentID"] = 17601,
            ["spellID"] = 86172,
            ["icon"] = 135897,
        },
    },
    [6] = {
        [1] = {
            ["name"] = "Holy Prism",
            ["row"] = 6,
            ["column"] = 1,
            ["talentID"] = 17605,
            ["spellID"] = 114165,
            ["icon"] = 613408,
        },
        [2] = {
            ["name"] = "Light's Hammer",
            ["row"] = 6,
            ["column"] = 2,
            ["talentID"] = 17607,
            ["spellID"] = 114158,
            ["icon"] = 613955,
        },
        [3] = {
            ["name"] = "Execution Sentence",
            ["row"] = 6,
            ["column"] = 3,
            ["talentID"] = 17609,
            ["spellID"] = 114157,
            ["icon"] = 613954,
        },
    },
};

talents.priest = {
    [1] = {
        [1] = {
            ["name"] = "Void Tendrils",
            ["row"] = 1,
            ["column"] = 1,
            ["talentID"] = 19752,
            ["spellID"] = 108920,
            ["icon"] = 537022,
        },
        [2] = {
            ["name"] = "Psyfiend",
            ["row"] = 1,
            ["column"] = 2,
            ["talentID"] = 19753,
            ["spellID"] = 108921,
            ["icon"] = 537021,
        },
        [3] = {
            ["name"] = "Dominate Mind",
            ["row"] = 1,
            ["column"] = 3,
            ["talentID"] = 19754,
            ["spellID"] = 605,
            ["icon"] = 136206,
        },
    },
    [2] = {
        [1] = {
            ["name"] = "Body and Soul",
            ["row"] = 2,
            ["column"] = 1,
            ["talentID"] = 19756,
            ["spellID"] = 64129,
            ["icon"] = 135982,
        },
        [2] = {
            ["name"] = "Angelic Feather",
            ["row"] = 2,
            ["column"] = 2,
            ["talentID"] = 19757,
            ["spellID"] = 121536,
            ["icon"] = 642580,
        },
        [3] = {
            ["name"] = "Phantasm",
            ["row"] = 2,
            ["column"] = 3,
            ["talentID"] = 19758,
            ["spellID"] = 108942,
            ["icon"] = 614257,
        },
    },
    [3] = {
        [1] = {
            ["name"] = "From Darkness, Comes Light",
            ["row"] = 3,
            ["column"] = 1,
            ["talentID"] = 19759,
            ["spellID"] = 109186,
            ["icon"] = 135981,
        },
        [2] = {
            ["name"] = "Mindbender",
            ["row"] = 3,
            ["column"] = 2,
            ["talentID"] = 19769,
            ["spellID"] = 123040,
            ["icon"] = 136214,
        },
        [3] = {
            ["name"] = "Solace and Insanity",
            ["row"] = 3,
            ["column"] = 3,
            ["talentID"] = 19761,
            ["spellID"] = 139139,
            ["icon"] = 612968,
        },
    },
    [4] = {
        [1] = {
            ["name"] = "Desperate Prayer",
            ["row"] = 4,
            ["column"] = 1,
            ["talentID"] = 19762,
            ["spellID"] = 19236,
            ["icon"] = 237550,
        },
        [2] = {
            ["name"] = "Spectral Guise",
            ["row"] = 4,
            ["column"] = 2,
            ["talentID"] = 19768,
            ["spellID"] = 112833,
            ["icon"] = 775463,
        },
        [3] = {
            ["name"] = "Angelic Bulwark",
            ["row"] = 4,
            ["column"] = 3,
            ["talentID"] = 19755,
            ["spellID"] = 108945,
            ["icon"] = 633042,
        },
    },
    [5] = {
        [1] = {
            ["name"] = "Twist of Fate",
            ["row"] = 5,
            ["column"] = 1,
            ["talentID"] = 19764,
            ["spellID"] = 109142,
            ["icon"] = 237566,
        },
        [2] = {
            ["name"] = "Power Infusion",
            ["row"] = 5,
            ["column"] = 2,
            ["talentID"] = 19765,
            ["spellID"] = 10060,
            ["icon"] = 135939,
        },
        [3] = {
            ["name"] = "Divine Insight",
            ["row"] = 5,
            ["column"] = 3,
            ["talentID"] = 19766,
            ["spellID"] = 109175,
            ["icon"] = 537078,
        },
    },
    [6] = {
        [1] = {
            ["name"] = "Cascade",
            ["row"] = 6,
            ["column"] = 1,
            ["talentID"] = 19767,
            ["spellID"] = 121135,
            ["icon"] = 612098,
        },
        [2] = {
            ["name"] = "Divine Star",
            ["row"] = 6,
            ["column"] = 2,
            ["talentID"] = 19760,
            ["spellID"] = 110744,
            ["icon"] = 537026,
        },
        [3] = {
            ["name"] = "Halo",
            ["row"] = 6,
            ["column"] = 3,
            ["talentID"] = 19763,
            ["spellID"] = 120517,
            ["icon"] = 632352,
        },
    },
};

talents.rogue = {
    [1] = {
        [1] = {
            ["name"] = "Nightstalker",
            ["row"] = 1,
            ["column"] = 1,
            ["talentID"] = 19233,
            ["spellID"] = 14062,
            ["icon"] = 132320,
        },
        [2] = {
            ["name"] = "Subterfuge",
            ["row"] = 1,
            ["column"] = 2,
            ["talentID"] = 19234,
            ["spellID"] = 108208,
            ["icon"] = 571317,
        },
        [3] = {
            ["name"] = "Shadow Focus",
            ["row"] = 1,
            ["column"] = 3,
            ["talentID"] = 19235,
            ["spellID"] = 108209,
            ["icon"] = 571316,
        },
    },
    [2] = {
        [1] = {
            ["name"] = "Deadly Throw",
            ["row"] = 2,
            ["column"] = 1,
            ["talentID"] = 19236,
            ["spellID"] = 26679,
            ["icon"] = 135430,
        },
        [2] = {
            ["name"] = "Nerve Strike",
            ["row"] = 2,
            ["column"] = 2,
            ["talentID"] = 19237,
            ["spellID"] = 108210,
            ["icon"] = 538537,
        },
        [3] = {
            ["name"] = "Combat Readiness",
            ["row"] = 2,
            ["column"] = 3,
            ["talentID"] = 19238,
            ["spellID"] = 74001,
            ["icon"] = 458725,
        },
    },
    [3] = {
        [1] = {
            ["name"] = "Cheat Death",
            ["row"] = 3,
            ["column"] = 1,
            ["talentID"] = 19239,
            ["spellID"] = 31230,
            ["icon"] = 132285,
        },
        [2] = {
            ["name"] = "Leeching Poison",
            ["row"] = 3,
            ["column"] = 2,
            ["talentID"] = 19240,
            ["spellID"] = 108211,
            ["icon"] = 538440,
        },
        [3] = {
            ["name"] = "Elusiveness",
            ["row"] = 3,
            ["column"] = 3,
            ["talentID"] = 19241,
            ["spellID"] = 79008,
            ["icon"] = 236284,
        },
    },
    [4] = {
        [1] = {
            ["name"] = "Cloak and Dagger",
            ["row"] = 4,
            ["column"] = 1,
            ["talentID"] = 19242,
            ["spellID"] = 138106,
            ["icon"] = 236285,
        },
        [2] = {
            ["name"] = "Shadowstep",
            ["row"] = 4,
            ["column"] = 2,
            ["talentID"] = 19243,
            ["spellID"] = 36554,
            ["icon"] = 132303,
        },
        [3] = {
            ["name"] = "Burst of Speed",
            ["row"] = 4,
            ["column"] = 3,
            ["talentID"] = 19244,
            ["spellID"] = 108212,
            ["icon"] = 538536,
        },
    },
    [5] = {
        [1] = {
            ["name"] = "Prey on the Weak",
            ["row"] = 5,
            ["column"] = 1,
            ["talentID"] = 19245,
            ["spellID"] = 131511,
            ["icon"] = 236278,
        },
        [2] = {
            ["name"] = "Paralytic Poison",
            ["row"] = 5,
            ["column"] = 2,
            ["talentID"] = 19246,
            ["spellID"] = 108215,
            ["icon"] = 538441,
        },
        [3] = {
            ["name"] = "Dirty Tricks",
            ["row"] = 5,
            ["column"] = 3,
            ["talentID"] = 19247,
            ["spellID"] = 108216,
            ["icon"] = 460691,
        },
    },
    [6] = {
        [1] = {
            ["name"] = "Shuriken Toss",
            ["row"] = 6,
            ["column"] = 1,
            ["talentID"] = 19248,
            ["spellID"] = 114014,
            ["icon"] = 135431,
        },
        [2] = {
            ["name"] = "Marked for Death",
            ["row"] = 6,
            ["column"] = 2,
            ["talentID"] = 19249,
            ["spellID"] = 137619,
            ["icon"] = 236364,
        },
        [3] = {
            ["name"] = "Anticipation",
            ["row"] = 6,
            ["column"] = 3,
            ["talentID"] = 19250,
            ["spellID"] = 114015,
            ["icon"] = 236280,
        },
    },
};

talents.shaman = {
    [1] = {
        [1] = {
            ["name"] = "Nature's Guardian",
            ["row"] = 1,
            ["column"] = 1,
            ["talentID"] = 19262,
            ["spellID"] = 30884,
            ["icon"] = 136060,
        },
        [2] = {
            ["name"] = "Stone Bulwark Totem",
            ["row"] = 1,
            ["column"] = 2,
            ["talentID"] = 19263,
            ["spellID"] = 108270,
            ["icon"] = 538572,
        },
        [3] = {
            ["name"] = "Astral Shift",
            ["row"] = 1,
            ["column"] = 3,
            ["talentID"] = 19264,
            ["spellID"] = 108271,
            ["icon"] = 538565,
        },
    },
    [2] = {
        [1] = {
            ["name"] = "Frozen Power",
            ["row"] = 2,
            ["column"] = 1,
            ["talentID"] = 19259,
            ["spellID"] = 63374,
            ["icon"] = 135776,
        },
        [2] = {
            ["name"] = "Earthgrab Totem",
            ["row"] = 2,
            ["column"] = 2,
            ["talentID"] = 19260,
            ["spellID"] = 51485,
            ["icon"] = 136100,
        },
        [3] = {
            ["name"] = "Windwalk Totem",
            ["row"] = 2,
            ["column"] = 3,
            ["talentID"] = 19261,
            ["spellID"] = 108273,
            ["icon"] = 538576,
        },
    },
    [3] = {
        [1] = {
            ["name"] = "Call of the Elements",
            ["row"] = 3,
            ["column"] = 1,
            ["talentID"] = 19275,
            ["spellID"] = 108285,
            ["icon"] = 538570,
        },
        [2] = {
            ["name"] = "Totemic Persistence",
            ["row"] = 3,
            ["column"] = 2,
            ["talentID"] = 19274,
            ["spellID"] = 108284,
            ["icon"] = 538573,
        },
        [3] = {
            ["name"] = "Totemic Projection",
            ["row"] = 3,
            ["column"] = 3,
            ["talentID"] = 19276,
            ["spellID"] = 108287,
            ["icon"] = 538574,
        },
    },
    [4] = {
        [1] = {
            ["name"] = "Elemental Mastery",
            ["row"] = 4,
            ["column"] = 1,
            ["talentID"] = 19271,
            ["spellID"] = 16166,
            ["icon"] = 136115,
        },
        [2] = {
            ["name"] = "Ancestral Swiftness",
            ["row"] = 4,
            ["column"] = 2,
            ["talentID"] = 19272,
            ["spellID"] = 16188,
            ["icon"] = 237576,
        },
        [3] = {
            ["name"] = "Echo of the Elements",
            ["row"] = 4,
            ["column"] = 3,
            ["talentID"] = 19273,
            ["spellID"] = 108283,
            ["icon"] = 538566,
        },
    },
    [5] = {
        [1] = {
            ["name"] = "Rushing Streams",
            ["row"] = 5,
            ["column"] = 1,
            ["talentID"] = 19268,
            ["spellID"] = 147074,
            ["icon"] = 135127,
        },
        [2] = {
            ["name"] = "Ancestral Guidance",
            ["row"] = 5,
            ["column"] = 2,
            ["talentID"] = 19269,
            ["spellID"] = 108281,
            ["icon"] = 538564,
        },
        [3] = {
            ["name"] = "Conductivity",
            ["row"] = 5,
            ["column"] = 3,
            ["talentID"] = 19270,
            ["spellID"] = 108282,
            ["icon"] = 538567,
        },
    },
    [6] = {
        [1] = {
            ["name"] = "Unleashed Fury",
            ["row"] = 6,
            ["column"] = 1,
            ["talentID"] = 19265,
            ["spellID"] = 117012,
            ["icon"] = 650636,
        },
        [2] = {
            ["name"] = "Primal Elementalist",
            ["row"] = 6,
            ["column"] = 2,
            ["talentID"] = 19266,
            ["spellID"] = 117013,
            ["icon"] = 651081,
        },
        [3] = {
            ["name"] = "Elemental Blast",
            ["row"] = 6,
            ["column"] = 3,
            ["talentID"] = 19267,
            ["spellID"] = 117014,
            ["icon"] = 651244,
        },
    },
};

talents.warlock = {
    [1] = {
        [1] = {
            ["name"] = "Dark Regeneration",
            ["row"] = 1,
            ["column"] = 1,
            ["talentID"] = 19279,
            ["spellID"] = 108359,
            ["icon"] = 537516,
        },
        [2] = {
            ["name"] = "Soul Leech",
            ["row"] = 1,
            ["column"] = 2,
            ["talentID"] = 19280,
            ["spellID"] = 108370,
            ["icon"] = 571320,
        },
        [3] = {
            ["name"] = "Harvest Life",
            ["row"] = 1,
            ["column"] = 3,
            ["talentID"] = 19281,
            ["spellID"] = 108371,
            ["icon"] = 537517,
        },
    },
    [2] = {
        [1] = {
            ["name"] = "Demonic Breath",
            ["row"] = 2,
            ["column"] = 1,
            ["talentID"] = 19284,
            ["spellID"] = 47897,
            ["icon"] = 236302,
        },
        [2] = {
            ["name"] = "Mortal Coil",
            ["row"] = 2,
            ["column"] = 2,
            ["talentID"] = 19285,
            ["spellID"] = 6789,
            ["icon"] = 607853,
        },
        [3] = {
            ["name"] = "Shadowfury",
            ["row"] = 2,
            ["column"] = 3,
            ["talentID"] = 19286,
            ["spellID"] = 30283,
            ["icon"] = 607865,
        },
    },
    [3] = {
        [1] = {
            ["name"] = "Soul Link",
            ["row"] = 3,
            ["column"] = 1,
            ["talentID"] = 19287,
            ["spellID"] = 108415,
            ["icon"] = 607854,
        },
        [2] = {
            ["name"] = "Sacrificial Pact",
            ["row"] = 3,
            ["column"] = 2,
            ["talentID"] = 19288,
            ["spellID"] = 108416,
            ["icon"] = 538538,
        },
        [3] = {
            ["name"] = "Dark Bargain",
            ["row"] = 3,
            ["column"] = 3,
            ["talentID"] = 19289,
            ["spellID"] = 110913,
            ["icon"] = 538039,
        },
    },
    [4] = {
        [1] = {
            ["name"] = "Blood Horror",
            ["row"] = 4,
            ["column"] = 1,
            ["talentID"] = 19290,
            ["spellID"] = 111397,
            ["icon"] = 538040,
        },
        [2] = {
            ["name"] = "Burning Rush",
            ["row"] = 4,
            ["column"] = 2,
            ["talentID"] = 19291,
            ["spellID"] = 111400,
            ["icon"] = 538043,
        },
        [3] = {
            ["name"] = "Unbound Will",
            ["row"] = 4,
            ["column"] = 3,
            ["talentID"] = 19292,
            ["spellID"] = 108482,
            ["icon"] = 571321,
        },
    },
    [5] = {
        [1] = {
            ["name"] = "Grimoire of Supremacy",
            ["row"] = 5,
            ["column"] = 1,
            ["talentID"] = 19293,
            ["spellID"] = 108499,
            ["icon"] = 538442,
        },
        [2] = {
            ["name"] = "Grimoire of Service",
            ["row"] = 5,
            ["column"] = 2,
            ["talentID"] = 19294,
            ["spellID"] = 108501,
            ["icon"] = 538444,
        },
        [3] = {
            ["name"] = "Grimoire of Sacrifice",
            ["row"] = 5,
            ["column"] = 3,
            ["talentID"] = 19295,
            ["spellID"] = 108503,
            ["icon"] = 538443,
        },
    },
    [6] = {
        [1] = {
            ["name"] = "Archimonde's Darkness",
            ["row"] = 6,
            ["column"] = 1,
            ["talentID"] = 19296,
            ["spellID"] = 108505,
            ["icon"] = 236402,
        },
        [2] = {
            ["name"] = "Kil'jaeden's Cunning",
            ["row"] = 6,
            ["column"] = 2,
            ["talentID"] = 19297,
            ["spellID"] = 137587,
            ["icon"] = 236418,
        },
        [3] = {
            ["name"] = "Mannoroth's Fury",
            ["row"] = 6,
            ["column"] = 3,
            ["talentID"] = 19298,
            ["spellID"] = 108508,
            ["icon"] = 236423,
        },
    },
};

talents.warrior = {
    [1] = {
        [1] = {
            ["name"] = "Juggernaut",
            ["row"] = 1,
            ["column"] = 1,
            ["talentID"] = 15775,
            ["spellID"] = 103826,
            ["icon"] = 132335,
        },
        [2] = {
            ["name"] = "Double Time",
            ["row"] = 1,
            ["column"] = 2,
            ["talentID"] = 16035,
            ["spellID"] = 103827,
            ["icon"] = 237377,
        },
        [3] = {
            ["name"] = "Warbringer",
            ["row"] = 1,
            ["column"] = 3,
            ["talentID"] = 15774,
            ["spellID"] = 103828,
            ["icon"] = 236319,
        },
    },
    [2] = {
        [1] = {
            ["name"] = "Enraged Regeneration",
            ["row"] = 2,
            ["column"] = 1,
            ["talentID"] = 16036,
            ["spellID"] = 55694,
            ["icon"] = 132345,
        },
        [2] = {
            ["name"] = "Second Wind",
            ["row"] = 2,
            ["column"] = 2,
            ["talentID"] = 15757,
            ["spellID"] = 29838,
            ["icon"] = 132175,
        },
        [3] = {
            ["name"] = "Impending Victory",
            ["row"] = 2,
            ["column"] = 3,
            ["talentID"] = 15758,
            ["spellID"] = 103840,
            ["icon"] = 589768,
        },
    },
    [3] = {
        [1] = {
            ["name"] = "Staggering Shout",
            ["row"] = 3,
            ["column"] = 1,
            ["talentID"] = 15768,
            ["spellID"] = 107566,
            ["icon"] = 132091,
        },
        [2] = {
            ["name"] = "Piercing Howl",
            ["row"] = 3,
            ["column"] = 2,
            ["talentID"] = 15769,
            ["spellID"] = 12323,
            ["icon"] = 136147,
        },
        [3] = {
            ["name"] = "Disrupting Shout",
            ["row"] = 3,
            ["column"] = 3,
            ["talentID"] = 15770,
            ["spellID"] = 102060,
            ["icon"] = 589118,
        },
    },
    [4] = {
        [1] = {
            ["name"] = "Bladestorm",
            ["row"] = 4,
            ["column"] = 1,
            ["talentID"] = 15759,
            ["spellID"] = 46924,
            ["icon"] = 236303,
        },
        [2] = {
            ["name"] = "Shockwave",
            ["row"] = 4,
            ["column"] = 2,
            ["talentID"] = 15760,
            ["spellID"] = 46968,
            ["icon"] = 236312,
        },
        [3] = {
            ["name"] = "Dragon Roar",
            ["row"] = 4,
            ["column"] = 3,
            ["talentID"] = 16037,
            ["spellID"] = 118000,
            ["icon"] = 642418,
        },
    },
    [5] = {
        [1] = {
            ["name"] = "Mass Spell Reflection",
            ["row"] = 5,
            ["column"] = 1,
            ["talentID"] = 15765,
            ["spellID"] = 114028,
            ["icon"] = 132358,
        },
        [2] = {
            ["name"] = "Safeguard",
            ["row"] = 5,
            ["column"] = 2,
            ["talentID"] = 15766,
            ["spellID"] = 114029,
            ["icon"] = 236311,
        },
        [3] = {
            ["name"] = "Vigilance",
            ["row"] = 5,
            ["column"] = 3,
            ["talentID"] = 19676,
            ["spellID"] = 114030,
            ["icon"] = 236318,
        },
    },
    [6] = {
        [1] = {
            ["name"] = "Avatar",
            ["row"] = 6,
            ["column"] = 1,
            ["talentID"] = 19138,
            ["spellID"] = 107574,
            ["icon"] = 613534,
        },
        [2] = {
            ["name"] = "Bloodbath",
            ["row"] = 6,
            ["column"] = 2,
            ["talentID"] = 19139,
            ["spellID"] = 12292,
            ["icon"] = 236304,
        },
        [3] = {
            ["name"] = "Storm Bolt",
            ["row"] = 6,
            ["column"] = 3,
            ["talentID"] = 19140,
            ["spellID"] = 107570,
            ["icon"] = 613535,
        },
    },
};

function NRC.getSpecData(classID, specID)
	if (specData[classID] and specData[classID][specID]) then
		local name = specData[classID][specID].name;
		local icon = specData[classID][specID].icon;
		local iconPath = specData[classID][specID].iconPath;
		return name, icon, iconPath;
	end
end

function NRC:getTalentData(class)
	class = string.lower(class);
	return talents[class];
end

function NRC:getTabData(class)
	class = string.lower(class);
	if (talents[class]) then
		local tabData = {};
		for k, v in ipairs(talents[class]) do
			tabData[k] = {
				numTalents = v.numtalents;
			};
		end
		return tabData;
	end
end

--TODO: Create database of glyph being applied spellIDs so we can detect the casts of people in group changing glyphs to reinspect.
--We need the actual glyph being applied ID https://www.wowhead.com/mop-classic/spell=124417/black-ice
NRC.glyphSpellIDs = {

};